#!/usr/bin/env bash
# shape-rotator-field-kit installer
#
# Bootstraps every tool in the kit on a fresh machine. Idempotent — safe
# to re-run to pick up updates after bumping a submodule pin.
#
# Usage:
#   bash setup.sh
#
# What it does:
#   1. Pulls every git submodule to its pinned commit.
#   2. Runs voxterm's own installer (macOS Apple-Silicon only; skipped elsewhere).
#   3. Sets up research-swarm in an isolated venv.
#   4. Creates ./bin/research-agent as a thin wrapper around that venv.
#   5. Copies research-swarm/.env.example to research-swarm/.env if missing.
#   6. Prints a short "what to do next" cheat sheet.
#
# What it does NOT do:
#   - Touch your shell config. You decide whether to add ./bin to PATH.
#   - Overwrite an existing .env file.
#   - Install anything globally other than what voxterm itself installs.

set -euo pipefail

# ── UI helpers ────────────────────────────────────────────────────────────

if [ -t 1 ]; then
  BOLD='\033[1m'; DIM='\033[2m'; CYAN='\033[36m'; GREEN='\033[32m'
  YELLOW='\033[33m'; RED='\033[31m'; RESET='\033[0m'
else
  BOLD=''; DIM=''; CYAN=''; GREEN=''; YELLOW=''; RED=''; RESET=''
fi

step()  { printf "${CYAN}▸${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}✓${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}!${RESET} %s\n" "$*" >&2; }
fail()  { printf "${RED}✗${RESET} %s\n" "$*" >&2; exit 1; }
heading() { printf "\n${BOLD}%s${RESET}\n" "$*"; }

# ── Locate self ───────────────────────────────────────────────────────────

KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$KIT_ROOT"

heading "shape-rotator-field-kit setup"
echo "root: $KIT_ROOT"

# ── 1. Prerequisites ─────────────────────────────────────────────────────

step "checking prerequisites"

command -v git >/dev/null 2>&1 || fail "git not found — install git first"

# Python: need 3.10+, prefer 3.12
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3; do
  if command -v "$candidate" >/dev/null 2>&1; then
    ver=$("$candidate" -c 'import sys; print("%d.%d" % sys.version_info[:2])')
    major=${ver%.*}; minor=${ver#*.}
    if [ "$major" -eq 3 ] && [ "$minor" -ge 10 ]; then
      PYTHON="$candidate"
      break
    fi
  fi
done
[ -n "$PYTHON" ] || fail "python 3.10+ required, none found"
ok "python: $PYTHON ($("$PYTHON" --version))"
ok "git:    $(git --version)"

# ── 2. Submodules ────────────────────────────────────────────────────────

step "syncing submodules"
git submodule update --init --recursive --quiet
ok "submodules at their pinned commits"
git submodule status | sed 's/^/  /'

# ── 3. voxterm (macOS Apple Silicon only) ────────────────────────────────

heading "voxterm"

if [ "$(uname)" != "Darwin" ]; then
  warn "voxterm requires macOS (Apple Silicon). Skipping on $(uname)."
elif [ "$(uname -m)" != "arm64" ]; then
  warn "voxterm requires Apple Silicon (arm64). Skipping on $(uname -m)."
elif command -v voxterm >/dev/null 2>&1; then
  ok "voxterm already installed at $(command -v voxterm)"
else
  step "running voxterm installer"
  if [ -f voxterm/install.sh ]; then
    bash voxterm/install.sh
  else
    # Fallback to upstream installer if the submodule doesn't ship one
    curl -fsSL https://raw.githubusercontent.com/dmarzzz/VoxTerm/main/install.sh | bash
  fi
  ok "voxterm installed"
fi

# ── 4. research-swarm ────────────────────────────────────────────────────

heading "research-swarm"

SWARM_DIR="$KIT_ROOT/research-swarm"
VENV="$SWARM_DIR/.venv"

if [ ! -d "$VENV" ]; then
  step "creating venv at $VENV"
  "$PYTHON" -m venv "$VENV"
fi

step "installing research-swarm into its venv"
"$VENV/bin/pip" install --quiet --upgrade pip >/dev/null
"$VENV/bin/pip" install --quiet -e "$SWARM_DIR"
ok "research-swarm installed"

if [ ! -f "$SWARM_DIR/.env" ]; then
  if [ -f "$SWARM_DIR/.env.example" ]; then
    cp "$SWARM_DIR/.env.example" "$SWARM_DIR/.env"
    ok "created research-swarm/.env (edit it to pick an LM)"
  fi
else
  ok "research-swarm/.env already exists — left alone"
fi

# ── 5. Wrapper scripts ───────────────────────────────────────────────────

heading "wrappers"

mkdir -p "$KIT_ROOT/bin"

cat > "$KIT_ROOT/bin/research-agent" <<EOF
#!/usr/bin/env bash
# Auto-generated by shape-rotator-field-kit/setup.sh
exec "$VENV/bin/research-agent" "\$@"
EOF
chmod +x "$KIT_ROOT/bin/research-agent"
ok "bin/research-agent  → $VENV/bin/research-agent"

# ── 6. Cheat sheet ───────────────────────────────────────────────────────

heading "done · try these"

cat <<EOF

  ${BOLD}./kit research "..."${RESET}        # DSPy ReAct research agent
  ${BOLD}./kit vox${RESET}                   # voxterm voice transcription TUI
  ${BOLD}./kit doctor${RESET}                # re-check everything is installed
  ${BOLD}./kit install-global${RESET}        # make 'rotate' callable from anywhere (optional)

To call from any directory as \`rotate\` (and let roaming agents find
this kit via \$SHAPE_ROTATOR_KIT_PATH), run:

  ./kit install-global

To switch LMs for research-swarm, edit ${DIM}research-swarm/.env${RESET}.
EOF

echo
ok "setup complete"
